spring.application.name=book-lending-api

# MySQL
spring.datasource.url=jdbc:mysql://${DB_HOST}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Flyway
spring.flyway.enabled=true

# Spring Data JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.show-sql=true
